services:
  afp:
    image: joaogsleite/afp:3.1.18
    build: .
    ports:
      - 548:548
    environment:
      AFP_USER: user
      AFP_PASSWORD: password
    volumes:
      - ./volumes/share:/media/share
      - ./volumes/timemachine:/media/timemachine